### ISSUE TITLE
Unable to launch the current demo

### ISSUE THREAD

**Issue by arukado-sama** [jimy-byerley/Tron-R-reboot-reloaded-#1]
Hello!

Let me begin by a huge thanks for creating such an amazing game, a game fans will certainly enjoy!
I tried to launch the current demo today, here are the problems I encountered (I'm on Windows 7 64 bit):
- The download for blender seems to fail cause build.bat searches wget in C:\Program Files (or ProgramData?)\wget\etc\wgetrc.

```
This is 64 Bit Operating System.
Downloading blender.
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = c:/progra~1/wget/etc/wgetrc
wget: missing URL
```
- So I downloaded blender 2.72 manually, set the archive name as blender.zip then build.bat worked fine for blender.
- Then I tried to launch Tron-R.bat. First of all, I had to change all slashes in backslashes inside this bat to get it work. And then unfortunately the game didn't launch because of errors with Python. I got a black screen in the Blender window.

```
E:\Downloads\Tron-R-reboot-reloaded--installed>Tron-R
Detected GL_ARB_texture_env_combine
Detected GL_ARB_texture_cube_map
Detected GL_ARB_multitexture
Detected GL_ARB_shader_objects
Detected GL_ARB_vertex_shader
Detected GL_ARB_fragment_shader
Detected GL_ARB_vertex_program
Detected GL_ARB_depth_texture
Detected GL_EXT_separate_specular_color
found bundled python: E:\Downloads\Tron-R-reboot-reloaded--installed\softwares\blender\2.72\python
Python script error - object 'bootloader', controller 'init':
Traceback (most recent call last):
  File "init_game.py", line 9, in <module>
IndexError: list index out of range
Python module can't be imported - object 'bootloader', controller 'scenes':
ImportError: No module named 'scenes'
Python module can't be imported - object 'bootloader', controller 'loader':
ImportError: No module named 'backup_manager'
Python module can't be imported - object 'bootloader', controller 'saver':
ImportError: No module named 'backup_manager'
```

Thanks in advance!

**Comment by jimy-byerley** [comment]
So, I corrected build.bat by replacing all slashes by backslashes (It was just a stupid error, from the linuxian I am ...)
The wget error is due to an other error on the blender URL variable name in build.bat: at line 35 I wrote %blednder64% instead of %blender64%. I corrected it.

The python error has a simple origin: No arguments should have been passed to the blenderplayer.exe. For a simple reason that's I wrote main.blend instead of menu.blend in Tron-R.bat at line 4. But of course It's the menu that must be started.
To be clear: Tron-R.bat have to open scenes/menu.blend, and menu.blend have to call scenes/main.blend with good commandline arguments.
I corrected this error too.

So all these errors are now corrected !
I finish by a short thanks because I can imagine that some people had already tried this game but never said to me that wasn't working.
I'm sorry for my bad english ...

**Comment by arukado-sama** [comment]
Don't worry about your english, it is good enough and it seems we are both French people (So you can speak french if you want to).
I better understand why it didn't work. Indeed some people never said it to you. But as I said in my mail I'm a huge TRON fan so I want this game to be perfect as possible, I'll test it on Windows during its whole development.
Unfortunately I'm not good enough to help you with your code, or it will take time to understand it but I have no time at the moment (I'm currently developing an important project on Symfony). Moreover I never used Blender.
I'll keep you informed of bugs, although there will always be bugs on the Grid.
Thanks again for creating such an awesome project.

**Comment by jimy-byerley** [comment]
I will still speak english for all notifications or important debug messages because everyone should be able to read it to learn my game. Here it's the time to close this report I think ...

Vous avez l'air d'avoir tout de meme de bonnes bases en programmation a ce que je vois (en tout cas pour utiliser l'invite de commande, python, ... et surtout contrairement a d'autres, d'avoir l'initiative de l'utiliser).
Quoi qu'il en soit, merci beaucoup des retours sur mon projet, cela fait toujours plaisir de savoir que d'autres partagent votre passion.
Effectivement il y aura toujours des bugs sur la grille :) : http://vignette3.wikia.nocookie.net/tron/images/8/89/Gridbug.png/revision/latest?cb=20140206225104

**Comment by arukado-sama** [comment]
Je comprends parfaitement pour l'utilisation de l'anglais dans les issues GitHub, j'imagine que l'on pourra utiliser le français par mail (et qu'on peut se tutoyer ?).
J'ai effectivement un certain niveau en programmation (C++, Java et RUBY) et en développement web, je viens de sortir d'une licence professionnelle Logiciels Libres.
J'ai toujours été fasciné par l'univers de TRON, le concept est unique et fantastique, si je peux aider d'une quelconque façon je le ferai. J'ai presque tout vu et joué de TRON (dont les scénarios majeurs TRON, TRON 2.0, TRON Evolution, TRON Uprising, TRON Legacy), techniquement il ne me reste plus qu'à lire les comics américains pour avoir la totalité des informations sur la Grille. J'ai encore énormément de choses à suggérer et de questions sur l'avenir de ce projet, j'utiliserai les mails, je continuerai tout de même à rapporter les bugs sur GitHub.
Bonne continuation !
